### ISSUE TITLE
Проблема подключения Threads к Swift-проекту

### ISSUE THREAD

**Issue by AndreyMirzoyan** [ThreadsMobileLib/threads-sdk-ios-releases#1]
Добрый день!
Пытаюсь подключить Threads (+PushServerAPI) к Swift-проекту.
Добавляю PushServerAPI.framework и Threads.framework в воркспейс.
И еще до создания Bridging-header-а возникает следующая ошибка сборки

```
ld: .../PushServerAPI.framework/PushServerAPI compiled with older version of Swift language (4.0) than previous files (unknown ABI version 0x06) file '.../PushServerAPI.framework/PushServerAPI' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Есть мысли почему так происходит и что надо сделать для корректной работы?

Используются:
Xcode 9.4.1
Swift 4.1

**Comment by Luten** [comment]
@AndreyMirzoyan, добрый день.
На данный момент проект не поддерживает Swift 4.1
В будущих релизах ее планируется реализовать, но сроки к сожалению пока назвать не могу.

**Comment by Luten** [comment]
@AndreyMirzoyan Поддержка Swift4.1 появилась - пока в отдельной ветке:
https://github.com/ThreadsMobileLib/threads-sdk-ios-releases/tree/swift4.1_xcode9.3%2B
Релиз: https://github.com/ThreadsMobileLib/threads-sdk-ios-releases/releases/tag/v2.38.101
