### ISSUE TITLE
Обновите Framework до Swift 5.2

### ISSUE THREAD

**Issue by venvear** [ThreadsMobileLib/threads-sdk-ios-releases#10]
Включите BUILD_LIBRARY_FOR_DISTRIBUTION = YES;

**Comment by alexejn** [comment]
https://tppr.me/lznEt

Соберите как xcframework,тогда такой ошибки не будет при следующих обновлениях swift

**Comment by Semplx** [comment]
Ничего не изменилось после обновления до 3.2.0.
