### ISSUE TITLE
Threads 3.4.0.  Missing required module 'libcmark'

### ISSUE THREAD

**Issue by venvear** [ThreadsMobileLib/threads-sdk-ios-releases#11]
При компиляции не может заимпортить Threads.
import Threads 
Missing required module 'libcmark'

**Comment by venvear** [comment]
![Teampaper Snap_2020-06-15 11-49-18@2x](https://user-images.githubusercontent.com/5576215/84637553-808ef480-aefe-11ea-9ee5-6b218fe9741d.png)

**Comment by Luten** [comment]
Проблема исправлена, релиз 3.4.0 перезалит
Если устанавливали через CocoaPods - нужно почистить кэш и установить 3.4.0 заного

**Comment by Luten** [comment]
Проблема исправлена, релиз 3.4.0 перезалит
Если устанавливали через CocoaPods - нужно почистить кэш и установить 3.4.0 заного
