### ISSUE TITLE
Не надо так.

### ISSUE THREAD

**Issue by alexejn** [ThreadsMobileLib/threads-sdk-ios-releases#7]
Зачем вы обернули 

  UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { (granted, _) in ... }

в свой метод Threads.threads().registerApplicationForRemoteNotificationsStandartOptions ? 

Не надо так делать. Как теперь управлять пушами если есть другие фреймворки в приложение которые тоже конфигурируются для пушей? 
как задать опции [.alert, .badge, .sound] ? 
Оригинальное АПИ от ios должно оставаться, конфигурируете свой фреймворк через UNUserNotificationCenter, а не UNUserNotificationCenter через себя

**Comment by vitkuzmenko** [comment]
Вас не обязывают использовать `registerApplicationForRemoteNotificationsStandartOptions`. Вы можете сделать свою регистрацию. Метод сделан для удобства, можете его не использовать. Главное реализуйте методы делегата `didRegisterForRemoteNotificationsWithDeviceToken` и т.д. согласно примеру

**Comment by Elshad** [comment]
Is `registerApplicationForRemoteNotificationsStandartOptions` override `UNUserNotificationCenter.current().requestAuthorization` which called before?
