### ISSUE TITLE
Обновите Framework до Swift 5.1.2 и включите Module Stability

### ISSUE THREAD

**Issue by hitman1711** [ThreadsMobileLib/threads-sdk-ios-releases#8]
Для включения Module Stability, нужно в настройках приложения включить флаг Build Libraries for Distribution

**Comment by Luten** [comment]
Поддержка Swift 5.1.2 реализована с версии 3.1.0
Build Libraries for Distibution планируется в версии 3.3.0, вместе с Swift5.2 - #10
